const DataMessage =[
    {
        id: 0,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Carlos Hernandez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:0,
        status:'enviado',
    },
    {
        id: 1,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Juan Pérez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:3,
        status:'recibido',
    },
    {
        id: 2,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Emilio Pérez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:0,
        status:'enviado',
    },    
    {
        id: 3,
        uri:'https://static.wikia.nocookie.net/fenshuiversomc/images/b/b7/Images.jpg/revision/latest?cb=20191110031150&path-prefix=es',
        username:'Ricardo Milos',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:5,
        status:'recibido',
    },    
    {
        id: 4,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Juan Pérez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:3,
        status:'recibido',
    },
    {
        id: 5,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Emilio Pérez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:0,
        status:'enviado',
    },    
    {
        id: 6,
        uri:'https://static.wikia.nocookie.net/fenshuiversomc/images/b/b7/Images.jpg/revision/latest?cb=20191110031150&path-prefix=es',
        username:'Ricardo Milos',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:5,
        status:'recibido',
    },    
    {
        id: 7,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Juan Pérez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:3,
        status:'recibido',
    },
    {
        id: 8,
        uri:'https://www.tooltyp.com/wp-content/uploads/2020/08/alex_icon.jpg',
        username:'Emilio Pérez',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:0,
        status:'enviado',
    },    
    {
        id: 9,
        uri:'https://static.wikia.nocookie.net/fenshuiversomc/images/b/b7/Images.jpg/revision/latest?cb=20191110031150&path-prefix=es',
        username:'Ricardo Milos',
        textmessage:'HolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHolaHola',
        date:'23/10/2022',
        quantity:5,
        status:'recibido',
    },    
]
export default DataMessage;